# REUSE copyright and license notices.
# Spec: https://reuse.software
# Tool: https://github.com/fsfe/reuse-tool (version 5.1.0)
# Run `reuse spdx` to generate per-file information

version = 1

# Catch-all, files may have more specific annotations
[[annotations]]
path = [
  "packages/**",
  "infra/**",
  "scripts/**",
  "*.lock",
  "*.txt",
  "*.toml",
  "*.json",
  "*.md",
  "*.cff",
  ".**",
]
SPDX-FileCopyrightText = "2025 Mayant Mukul"
SPDX-License-Identifier = "AGPL-3.0-or-later"

# Example projects include Apache-2.0 fuzz drivers from OSS-Fuzz
# Individual files may have more specific annotations
[[annotations]]
path = "examples/**"
SPDX-FileCopyrightText = "2023 Google LLC"
SPDX-License-Identifier = "Apache-2.0"

# These are OSS-Fuzz test cases that have crashed in the past
[[annotations]]
path = "examples/**/testcases/**"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "2025"

# Generated bundles we keep in here

[[annotations]]
path = "examples/fast-xml-parser/fxp.full.js"
SPDX-FileCopyrightText = "2017 Amit Kumar Gupta"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "examples/jimp/jimp.browser.js"
SPDX-FileCopyrightText = "2018 Oliver Moran"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "examples/jpeg-js/jpeg-js.bundle.js"
SPDX-FileCopyrightText = "2014 Eugene Ware"
SPDX-License-Identifier = "BSD-3-Clause"

# @railcar/support is Apache-2.0
[[annotations]]
path = [
  "packages/support/**",
]
SPDX-FileCopyrightText = "2025 Mayant Mukul"
SPDX-License-Identifier = "Apache-2.0"

# Documentation
[[annotations]]
path = [
  "notes/**",
  "docs/**"
]
SPDX-License-Identifier = "GFDL-1.3-or-later"
SPDX-FileCopyrightText = "2025 Mayant Mukul"
