[package]
name = "railcar_cli"
version = "0.1.9"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
serde = "1.0.216"
serde_json = "1.0.134"
clap = { version = "4.5.32", features = ["derive"] }
railcar = { path = "../fuzzer" }
env_logger.workspace = true
log.workspace = true
anyhow.workspace = true
libafl.workspace = true
libafl_bolts.workspace = true

[[bin]]
name = "railcar"
path = "src/main.rs"
