[package]
name = "railcar"
version = "0.1.9"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
serde = "1.0.216"
serde_json = "1.0.134"
serde_bytes = "0.11.17"
static_assertions = "1.1.0"
rmp-serde = "1.3.0"
chrono = "0.4.42"
rusqlite = "0.37.0"
nix = { version = "0.29.0", features = ["process", "signal", "fs"] }
memory-stats = { version = "1.2.0", features = ["always_use_statm"] }
uuid = { version = "1.18.1", features = ["serde", "v4"] }
libafl = { workspace = true, features = ['track_hit_feedbacks'] }
libafl_bolts.workspace = true
log.workspace = true
anyhow.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "mutation"
harness = false
