[package]
name = "railcar_graph"
version = "0.1.9"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
serde = "1.0.216"
serde_json = "1.0.134"
static_assertions = "1.1.0"
rmp-serde = "1.3.0"
serde_bytes = "0.11.17"
chrono = "0.4.42"
rusqlite = "0.37.0"
libafl.workspace = true
libafl_bolts.workspace = true
log.workspace = true
anyhow.workspace = true
