[package]
name = "railcar_graph"
version = "0.1.9"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
serde = "1.0.216"
serde_json = "1.0.134"
static_assertions = "1.1.0"
metrics = { path = "../metrics" }
rmp-serde = "1.3.0"
serde_bytes = "0.11.17"
libafl.workspace = true
libafl_bolts.workspace = true
