[package]
name = "railcar_tools"
version = "0.1.9"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
glob = "0.3.2"
railcar = { path = "../fuzzer" }
serde = "1.0.216"
serde_json = "1.0.134"
regex = "1.11.1"
rmp-serde = "1.3.0"
clap = { version ="4.5.32", features = ["derive"] }
libafl.workspace = true
log.workspace = true
env_logger.workspace = true
anyhow.workspace = true

[lib]
name = "tools"
path = "src/lib.rs"

[[bin]]
name = "viz"
path = "src/viz.rs"

[[bin]]
name = "covdiff"
path = "src/covdiff.rs"

[[bin]]
name = "convert"
path = "src/convert.rs"

[[bin]]
name = "covmerge"
path = "src/covmerge.rs"

[[bin]]
name = "coverage"
path = "src/coverage.rs"
